version: '2'

services:
  db:
    image: healthcareblocks/mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: anothersecret
    expose:
      - "3306"
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
  app:
    depends_on:
      - db
    image: dockerhub-org-name/my-app
    expose:
      - "9000"
    restart: always
    volumes:
      - /app
  nginx:
    depends_on:
      - app
    image: healthcareblocks/nginx
    environment:
      NGINX_BACKEND_SERVER_ADDRESS: app
      NGINX_BACKEND_SERVER_PORT: 9000
      NGINX_ROOT_DIR: /app/public
      NGINX_SERVER_TYPE: php
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/ssl/certs/dhparam.pem:/nginx/ssl/dhparam.pem
      - /etc/ssl/certs/app.crt:/nginx/ssl/app.crt
      - /etc/ssl/private/app.key:/nginx/ssl/app.key
    volumes_from:
      - app
